In [ ]:
#Write a Python Program to Add Two Matrices

In [17]:
def add_matrix(m1,m2):
    if len(m1) != len(m2):
        print("Enter same lenght matrix")
    else:
        print(m1, "+", m2, "=")
        result = [[m1[i][j] + m2[i][j]  for j in range(len(m1[0]))] for i in range(len(m1))]
        for r in result:
            print(r)

import numpy as np
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
print("Enter the entries in a single line (separated by space): ")
m1 = list(map(int, input("Enter first matrix elements:").split()))
m2 = list(map(int, input("Enter second matrix elements:").split()))
ma1 = np.array(m1).reshape(R, C)
ma2 = np.array(m2).reshape(R, C)
add_matrix(ma1,ma2)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
Enter first matrix elements:1 2 3 4
Enter second matrix elements:1 2 3 4
[[1 2]
 [3 4]] + [[1 2]
 [3 4]] =
[2, 4]
[6, 8]


In [ ]:
# Write a Python Program to Multiply Two Matrices

In [3]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [ ]:
#Write a Python Program to Transpose a Matrix?

In [2]:
import numpy as np

arr1 = np.array([[4,5,6], [6,4,5]])

print(f'Original Array:\n{arr1}')

arr1_transpose = arr1.transpose()

print(f'Transposed Array:\n{arr1_transpose}')

Original Array:
[[4 5 6]
 [6 4 5]]
Transposed Array:
[[4 6]
 [5 4]
 [6 5]]


In [ ]:
#Write a Python Program to Sort Words in Alphabetic Order

In [16]:
list_words = input("Enter words:").split()
list_words
list_words.sort()
print(list_words)

Enter words:ram app
['app', 'ram']


In [ ]:
#Write a Python Program to Remove Punctuation From a String?

In [19]:
import string

str1 = input("Enter your string:")
new_string = str1.translate(str.maketrans('', '', string.punctuation))

print(new_string)


Enter your string:ram,suresh!
ramsuresh
